Set or force a current package base
because wercker do not recognize it on continuous integration

```
 File "/pipeline/source/pywatch/settings/ci.py", line 2, in <module>
    from base import *
ImportError: No module named 'base'
```